CREATE OR REPLACE VIEW `inm-iar-data-warehouse-dev.lease_tracker.lease_tracker_raw_data` AS (
    SELECT
        NULL AS `_Null_`,
        retail_invoice_id AS `Retail Invoice ID`,
        wholesale_invoice_id AS `Wholesale Invoice ID`,
        account_number AS `Account_Number__c`,
        account_period_of_first_wholesale_invoice_yyyymm
            AS `Account_period_of_first_invoice_YYYYMM__c`,
        approval_document AS `Approval_Document__c`,
        approval_document_status AS `Approval_Document_Status__c`,
        approval_status_change_date AS `Approval_Status_Change_Date__c`,
        assessment_comments AS `Assessment_Comments__c`,
        billing_acknowledgement_of_approval_docu AS `Billing_Acknowledgement_of_Approval_Docu__c`,
        billing_completed AS `Billing_Completed__c`,
        bupa AS `BUPA__c`,
        can_be_accommodated AS `Can_be_accommodated__c`,
        channel_no_2 AS `Channel_No2__c`,
        channel_weeks_charge AS `Channel_Weeks_Charge__c`,
        channel_weeks_trust_comm_l_tac AS `Channel_Weeks_TrustComm_L_TAC__c`,
        commercials_confirmed AS `Commercials_Confirmed__c`,
        NULL AS `Company_ID__c`,
        NULL AS `Consumed_Amount__c`,
        NULL AS `Consumed_Amount_Per__c`,
        NULL AS `Contract_Daily_Rate__c`,
        contract_duration AS `Contract_Duration_Days__c`,
        contract_progress AS `Contract_Progress__c`,
        contract_progress_comments AS `Contract_progress_Comments__c`,
        contract_sent_to_lsp AS `Contract_sent_to_LSP__c`,
        contract_signed_by_lsp AS `Contract_signed_by_LSP__c`,
        NULL AS `Contract_SLA__c`,
        contracts_acknowledgement_of_approval_do AS `Contracts_Acknowledgement_of_Approval_Do__c`,
        conus_discount_trust_comm_l_tac AS `CONUS_Discount_TrustComm_L_TAC__c`,
        NULL AS `Count__c`,
        created_date AS `CreatedDate`,
        credit_check_comments AS `Credit_check_comments__c`,
        credit_limit_approved AS `Credit_limit_approved__c`,
        credit_rejected AS `Credit_Rejected__c`,
        NULL AS `Credit_SLA__c`,
        disaster_recovery_charge AS `Disaster_Recovery_Charge__c`,
        disaster_recovery_with_spectrum AS `Disaster_Recovery_with_Spectrum__c`,
        disaster_recovery_without_spectrum AS `Disaster_Recovery_without_Spectrum__c`,
        document_approval_status_changed_date AS `Document_Approval_Status_Changed_Date__c`,
        due_date AS `Due_Date__c`,
        end_user_organisation AS `End_User_Organisation__c`,
        escalation_reason AS `Escalation_Reason__c`,
        NULL AS `External_Sale_Profit_Center__c`,
        forward_bandwidth_k_hz AS `Forward_Bandwidth_kHz__c`,
        forward_data_rates_kbps AS `Forward_Data_Rates_kbps__c`,
        gx_email_alert_recursion_stop AS `GX_Email_Alert_Recursion_Stop__c`,
        host_radio_3 AS `Host_Radio3__c`,
        initial_request_date AS `Initial_Request_Date__c`,
        NULL AS `Internal_Sale_Profit_Center__c`,
        is_this_application_subject_to AS `Is_this_application_subject_to__c`,
        is_deleted AS `IsDeleted`,
        isol_gm AS `ISOL_GM__c`,
        NULL AS `LAF_published__c`,
        last_modified_date AS `LastModifiedDate`,
        lease_end_time AS `Lease_End_Time__c`,
        lease_request_number AS `Lease_Request_Number__c`,
        lease_start_time AS `Lease_Start_Time__c`,
        lease_type AS `Lease_Type__c`,
        leasing_cc_emails AS `Leasing_CC_emails__c`,
        lspa_contract_no AS `LSPA_Contract_No__c`,
        NULL AS `Material_Code__c`,
        number_of_beams AS `Number_of_Beams__c`,
        other_technical_details_required AS `Other_Technical_Details_Required__c`,
        pmp_volume_discount AS `PMP_Volume_Discount__c`,
        power_d_bw AS `Power_dBW__c`,
        pre_sales_required AS `Pre_Sales_Required__c`,
        price_plan AS `Price_Plan__c`,
        pricing_acknowledgement_of_approval_docu AS `Pricing_Acknowledgement_of_Approval_Docu__c`,
        NULL AS `Pricing_SLA__c`,
        primary_les_sas AS `Primary_LES_SAS__c`,
        project_id AS `Project_ID__c`,
        project_name AS `Project_Name__c`,
        record_type_id AS `RecordTypeId`,
        NULL AS `Retail_Account_Codes__c`,
        retail_bill_interval_comments AS `Retail_Bill_Interval_Comments__c`,
        retail_billing_date_entered AS `Retail_Billing_entered__c`,
        retail_billing_status AS `Retail_Billing_Status__c`,
        NULL AS `Retail_Consumed_Amount__c`,
        NULL AS `Retail_Consumed_Amount_Per__c`,
        NULL AS `Retail_Margin__c`,
        return_bandwidth_khz AS `Return_Bandwidth_kHz__c`,
        return_data_rates_kbps AS `Return_Data_Rates_kbps__c`,
        satellite AS `Satellite__c`,
        secondary_les_sas AS `Secondary_LES_SAS__c`,
        send_lrf_to_ops AS `Send_LRF_to_Ops__c`,
        send_to_contracts AS `Send_to_Contracts__c`,
        special_comments AS `Special_Comments__c`,
        special_terms_and_conditions_applicable AS `Special_Terms_and_Conditions_Applicable__c`,
        spot_beam_equivalent AS `Spot_Beam_Equivalent__c`,
        spot_beam_equivalent_4 AS `Spot_Beam_Equivalent4__c`,
        status_changed_date AS `Status_Changed_Date__c`,
        NULL AS `Status_Report__c`,
        system_modstamp AS `SystemModstamp`,
        NULL AS `Technical_BD_SLA__c`,
        term_discount AS `Term_Discount__c`,
        total_value_of_the_order AS `Total_Value__c`,
        trust_comm_weeks AS `TrustComm_Weeks__c`,
        type_of_beam AS `Type_of_Beam__c`,
        NULL AS `Wholesale_Account_Code__c`,
        wholesale_bill_interval_comments AS `Wholesale_Bill_Interval_Comments__c`,
        wholesale_billing_comments AS `Wholesale_billing_comments__c`,
        wholesale_billing_engine AS `Wholesale_billing_engine__c`,
        wholesale_billing_entered AS `Wholesale_billing_entered__c`,
        wholesale_billing_status AS `Wholesale_Billing_Status__c`,
        wholesale_monthly_minimum_charge AS `Wholesale_Monthly_Minimum_Charge__c`,
        wholesale_or_retail_formula AS `Wholesale_or_Retail_Formula__c`,
        account_manager AS `Account Manager`,
        business_unit AS `Business Unit`,
        ssp_number AS `SSP number`,
        lease_update_status AS `Lease Update Status`,
        lsp AS `LSP`,
        approval_document_id AS `Approval Document ID`,
        end_date_of_current_lease AS `End Date of Current Lease`,
        internal_external AS `Internal or External`,
        land_aero_maritime AS `Land Aero Maritime`,
        service_type AS `Service Type`,
        start_date_of_current_lease AS `Start Date of Current Lease`,
        lsr AS `LSR`,
        end_customer AS `End Customer`,
        retail_bill_interval AS `Retail Bill Interval`,
        retail_contract_value AS `Retail Contract Value`,
        retail_periodic_payment_amount AS `Retail Periodic Payment Amount`,
        retail_pricing_comments AS `Retail Pricing Comments`,
        revenue_recognition_basis AS `Revenue Recognition Basis`,
        wholesale_bill_interval AS `Wholesale Bill Interval`,
        wholesale_contract_value AS `Wholesale Contract Value`,
        wholesale_periodic_payment_amount AS `Wholesale Periodic Payment Amount`,
        wholesale_pricing_comments AS `Wholesale Pricing Comments`,
        customer_name AS `Customer_Name__c`,
        NULL AS `Contract_Days_Time_Difference__c`,
        NULL AS `Contract_No_of_Days__c`,
        NULL AS `Contract_date_difference__c`,
        disaster_recovery_frequency_reservation AS `Disaster_Recovery_Frequency_Reservation__c`,
        forward_bandwidth_mhz AS `Forward_Bandwidth_MHz__c`,
        forward_data_rates_mbps AS `Forward_Data_Rates_Mbps__c`,
        NULL AS `ISOL_GM_formula__c`,
        reserved_capacity AS `Reserved_Capacity__c`,
        NULL AS `Retail_Consumed_Amount_Left__c`,
        return_bandwidth_mhz AS `Return_Bandwidth_MHz__c`,
        return_data_rates_mbps AS `Return_Data_Rates_Mbps__c`,
        NULL AS `Wholesale_Consumed_Amount_Left__c`,
        optional_renewal_years_pricing_the_same AS `Optional_Renewal_Years_Pricing_the_Same__c`,
        standard_billing_interval AS `Standard_Billing_Interval__c`,
        year_10 AS `Year_10__c`,
        year_1 AS `Year_1__c`,
        year_2 AS `Year_2__c`,
        year_3 AS `Year_3__c`,
        year_4 AS `Year_4__c`,
        year_5 AS `Year_5__c`,
        year_6 AS `Year_6__c`,
        year_7 AS `Year_7__c`,
        year_8 AS `Year_8__c`,
        year_9 AS `Year_9__c`,
        NULL AS `Retail_Contract_Daily_Rate__c`,
        NULL AS `Wholesale_Contract_Daily_Rate__c`,
        NULL AS `Approval_Doc_Status_Empty_to_Value__c`,
        approval_document_status_date_capture AS `Approval_Document_Status_Date_Capture__c`,
        approvl_doc_status_date_capture_empty AS `Approvl_Doc_Status_Date_Capture_Empty__c`,
        NULL AS `Completed_in_Billing_SLA__c`,
        NULL AS `Lease_Status_Solution_to_Pricing_TimeDif__c`,
        NULL AS `Lease_Update_Status_Billing_Day__c`,
        NULL AS `Lease_Update_Status_Billing__c`,
        lease_update_status_solution_engineering AS `Lease_Update_Status_Solution_Engineering__c`,
        lease_update_status_pricing AS `Lease_update_Status_Pricing__c`,
        NULL AS `PG_BD_SLA__c`,
        NULL AS `Retail_Billing_Completed_in_SLA__c`,
        type_of_beam_equivalent AS `Type_of_Beam_Equivalent__c`,
        uid_unbilled_amount_retail_formula AS `UID_Unbilled_Amount_Retail_Formula__c`,
        uid_unbilled_amount_wholesale_new AS `UID_Unbilled_Amount_Wholesale_New__c`,
        wholesale_billing_entered AS `Wholesale_billing_entered_Day__c`,
        retail_uid_billed_amount AS `UID_Billed_Amount_Retail_Rollup__c`,
        wholesale_uid_billed_amount AS `UID_Billed_Amount_Wholesale_Rollup__c`,
        po_amount AS `PO_Amount__c`,
        call_off_lease AS `Call-Off Lease`,
        current_month AS `Current Month`,
        accrual_date AS `Accrual Date`
    FROM
        `inm-iar-data-warehouse-dev.lease_tracker.lease_tracker_base`
    WHERE lease_update_status != 'Lease Cancelled'
);
